version: '3.8'

services:
  telegram_bot:
    build: telegram-bot-simple
    container_name: telegram-bot-simple
    image: ${TELEGRAMBOT_IMAGE_BUILD:-sfarhad/telegram-bot-simple:2.0.0}
    ports:
      - "${SSL_PORT:-443}:443"
    environment:
      - SSL_PORT=${SSL_PORT:-443}
      - IP_ADDRESS=${IP_ADDRESS}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    volumes:
      - ./telegram-bot-simple/output:/app/output
